# Etapa 1: Build
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app

# Copiar os arquivos de projeto e de solução
COPY PetroMap/PetroMap.csproj ./PetroMap/
COPY PetroMap.sln ./

# Restaurar as dependências
RUN dotnet restore

# Copiar o restante do código
COPY . .

# Publicar o projeto
RUN dotnet publish -c Release -o /app/publish

# Etapa 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app

# Copiar a pasta publish do container de build
COPY --from=build /app/publish .

# Definir a URL do ASP.NET Core
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

# Definir o ponto de entrada
ENTRYPOINT ["dotnet", "PetroMap.dll"]
